FROM ubuntu 
RUN apt update 
RUN apt install -y apache2
RUN apt install -y apache2-utils 
# install php and sqlite
RUN apt install -y php7.4
RUN apt install -y php7.4-sqlite3
RUN apt install -y php7.4-curl
RUN apt install -y software-properties-common
RUN add-apt-repository ppa:ondrej/php
RUN apt install -y sqlite3
RUN apt clean 
EXPOSE 80

COPY seinn.is.conf /etc/apache2/sites-available/seinn.is.conf
RUN rm -rf /etc/apache2/sites-enabled/000-default.conf
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
RUN a2enmod rewrite
RUN a2dissite 000-default
RUN a2ensite seinn.is
RUN service apache2 restart

 php:7.4-apache
WORKDIR /var/www
COPY index.html seinn.is/index.html
COPY fetch.php seinn.is/fetch.php
COPY neareststop.php seinn.is/neareststop.php

 python:latest
RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir requests
COPY gtfs.py seinn.is/gtfs.py
CMD ["python", "seinn.is/gtfs.py"]

ENTRYPOINT ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]